name: 'Build And Test'

on: 
  workflow_dispatch:
  push:
  # pull_request:
  #   branches:
  #     - master
concurrency:
  # Latest code is always prioritized to run per workflow per branch. 
  #   If a new push comes in on a branch, a already running workflow it is canceled and latest code runs.
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
env: 
  ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER: true
jobs:
  build-and-test:
    runs-on: [self-hosted, linux]
    # Action to use Dockerfile Setup fron runtimeverification/devops-actions
    steps:
      - name: ENV Setup / Build
        id: Setup
        uses: runtimeverification/devops-actions
        with: 
          entrypoint: '/bin/bash'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run Tests
        run: cat /VERSION

      - name: Publish Report? Or Data for Download 